Form section pair programing team
AbdulSalamAbro/personal-portfolio pull request #4
Opened 2023-05-10 18:21 UTC by AbdulSalamAbro

#Create_form_Section

*create the foother tags.
*create the foother title.
*create title information.
*create the labels container.
*create the labels and inputs tags.
*add HTML validation.
*create the button
*create the form style.
*use linter to detect and resolve CSS error.

2023-05-10 19:31 UTC, taldr27 requested changes
# Status: Required Changes ♻️♻️
Hello team, @AbdulSalamAbro, @WalidAmmarAli , 

Good job so far! 
You're making good progress on the project, but some issues still need to be addressed before you can move on to the next stage. Keep up the good work! 💪

![almost-there](https://media.giphy.com/media/l1JojjVanlckKIHMQ/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Nice work using Formspree.
✅ Good design of your contact section.


## Required Changes ♻️
_Check the comments under the review._

------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-10 19:31 UTC, taldr27 commented on index.html
> +    </section>
Great job on your contact section and form! 👍 I just wanted to **offer a couple of suggestions to help make your project even better** and closer to the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&t=U96fbZKLtw5V1wBA-0) provided:

- [ ] Could you kindly **check the spacing between** your `contact` and `about me` sections? It seems a bit too large compared to the template provided. 💯
- [ ] It would also be great if you could make your inputs wider, as they appear a bit small compared to the template. 🔍
- [ ] Don't forget to check the color of the placeholders as well, to ensure they match the [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=39-122&t=U96fbZKLtw5V1wBA-0). 🎯
- [ ] Additionally, it would be great if you could add the correct `background image` to your `contact` section to **make it look more professional and visually appealing**. This will bring it closer to the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=39-122&t=U96fbZKLtw5V1wBA-0) and give your project a polished finish. 🙌
  
  ### Your design (375x779):
  ![image](https://github.com/AbdulSalamAbro/personal-portfolio/assets/107952724/2debcad5-f67d-4447-b86a-ebbea483f8e1)

  
  ### Figma design:
  ![image](https://github.com/AbdulSalamAbro/personal-portfolio/assets/107952724/8eacfcbe-5bf9-4da6-ae67-7fb2ff51affe)
  
  ----
  _Just a quick reminder: for this project, it's important to try your best to follow the Figma template as closely as possible. You're doing great so far, and it's just a matter of making sure everything aligns with the template provided._
  ![image](https://user-images.githubusercontent.com/107952724/235323387-c50f856e-6774-45ca-ae81-7304c8b62709.png)

2023-05-10 20:47 UTC, AbdulSalamAbro commented on index.html
> +    </section>
Thankyou for your review and feedback we just updated and submit pull request again

2023-05-10 21:08 UTC, usorfaitheloho requested changes
> Hi @AbdulSalamAbro  ,
> 
> Great job for implemented the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍
> 
> ## Highlights 👏🏻
> ✔️ No linters error ✔️ You used correct Git Hub-Flow. ✔️ Good README ✔️ Good Commit Messages
> 
> ![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) [ ![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) ](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) [ ](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)
> 
> ## Required Changes ♻️
> _Check the comments below the review._
> 
> * [ ]  Kindly I recommend you to update your READEME file to include the **"Feature section "**  including 1-3 potential features to be added and please before push the READEME file to main branch kindly make sure that you update in your feature branch(here).
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 21:08 UTC, usorfaitheloho commented on index.html
> +      </form>
Great job on implementing the `form section` of your project. As suggested by the previous reviewer please I'd suggest you reduce the space between the `about` section and the `contact` section, and also use the placeholder text color as shown in the Figma design to enable you have an appealing design that would attract hiring managers 😄 

Your design:

![image](https://github.com/AbdulSalamAbro/personal-portfolio/assets/20537712/21b1203a-ae58-4d81-98ff-9f5432c64cb1)

Figma design :
![image](https://github.com/AbdulSalamAbro/personal-portfolio/assets/20537712/f7c38d27-d08f-4ddb-9af5-bd1b13713a75)

2023-05-12 12:37 UTC, jasonfelice approved these changes
Hi @AbdulSalamAbro, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"><img  src="https://media2.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=ecf05e472vkr75z01b5qlseyap0ylpyn6krdcf0fokyey0cx&rid=giphy.gif&ct=g"/></p>

## Highlights
No Linter Errors✔️
Professional Documentation✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 18:22 UTC, merged